#pragma once
#include <Windows.h>
#include <TlHelp32.h>
#include <iostream>
#include <thread>
#include <cstdint>
#include <fstream>
#include <string>
#include "utils/hooker/hooker.h"
#include "utils/offsets.h"
#include "utils/utils.h"
#include "utils/stubs.h"
#include "utils/globals.h"
#include "utils/skCrypt.h"
#include "utils/auth.hpp"
#include "utils/utils.hpp"
#include "utils/gui/gui.h"
#include "utils/gui/imgui/imgui.h"